/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-01-24 10:45:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class messages_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/increpas/spring/example/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch19_project_mavenwebsite/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1544682339013L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" \r\n");
      out.write(" \t  content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Maven Company Signup Messages Page</title>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/lib/w3-colors-win8.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.jumbotron{\r\n");
      out.write("\t\tmargin-bottom: 5px;\r\n");
      out.write("\t\tbackground-color:red;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#myProgress {\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  background-color: #ddd;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#myBar {\r\n");
      out.write("\t  width: 1%;\r\n");
      out.write("\t  height: 30px;\r\n");
      out.write("\t  background-color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.collapsible {\r\n");
      out.write("\t  background-color: #aaa69d;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  cursor: pointer;\r\n");
      out.write("\t  padding: 18px;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  border: none;\r\n");
      out.write("\t  text-align: left;\r\n");
      out.write("\t  outline: none;\r\n");
      out.write("\t  font-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.active, .collapsible:hover {\r\n");
      out.write("\t  background-color: #555;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.collapsible:after {\r\n");
      out.write("\t  content: '\\002B';\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  font-weight: bold;\r\n");
      out.write("\t  float: right;\r\n");
      out.write("\t  margin-left: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.active:after {\r\n");
      out.write("\t  content: \"\\2212\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.content {\r\n");
      out.write("\t  padding: 0 18px;\r\n");
      out.write("\t  max-height: 0;\r\n");
      out.write("\t  overflow: hidden;\r\n");
      out.write("\t  transition: max-height 0.2s ease-out;\r\n");
      out.write("\t  background-color: #f5f6fa;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.danger {\r\n");
      out.write("\t  background-color: #ffdddd;\r\n");
      out.write("\t  border-left: 6px solid #f44336;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.w3-container{\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#redone{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#redone::first-line {\r\n");
      out.write("\t  color: #ff0000;\r\n");
      out.write("\t  font-variant: small-caps;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.footer{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tline-height: 100px;\r\n");
      out.write("\t\tbackground-color: #444;\r\n");
      out.write("\t\tcolor: red;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top: 200px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t<h1 style=\"font-size:xx-large;color:white;\" title=\"Maven Company 회원가입시 주의사항\"><i class='fas fa-exclamation' style='font-size:36px;color:yellow;'></i> Maven Company Signup Messages Page</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"w3-container\">\r\n");
      out.write("\t\t\t\t\t<button onclick=\"document.getElementById('id01').style.display='block'\" class=\"w3-button w3-black\"><i class=\"fa fa-bug\" style=\"font-size:20px\"></i> Open Modal Message</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  <div id=\"id01\" class=\"w3-modal\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"w3-modal-content\">\r\n");
      out.write("\t\t\t\t\t      <header class=\"w3-container w3-teal\"> \r\n");
      out.write("\t\t\t\t\t        <span onclick=\"document.getElementById('id01').style.display='none'\" \r\n");
      out.write("\t\t\t\t\t        class=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("\t\t\t\t\t        <h2 style=\"text-align:center;\"><i class=\"fa fa-yelp\" style=\"font-size:24px;color:buttonhighlight;\"></i> Model Message !</h2>\r\n");
      out.write("\t\t\t\t\t      </header>\r\n");
      out.write("\t\t\t\t\t      <div class=\"w3-container\">\r\n");
      out.write("\t\t\t\t\t        <div class=\"w3-panel w3-win8-crimson\">\r\n");
      out.write("\t\t\t\t\t\t\t    <h2 style=\"text-align:center;\"><i class='fas fa-info-circle' style='font-size:24px;color:orange;'></i> 사내 정보보안 안내</h2>\r\n");
      out.write("\t\t\t\t\t\t\t    <h4 style=\"text-align:center;\">사용자 계정 관리 안내</h4>\r\n");
      out.write("\t\t\t\t\t\t\t    <ol>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<li>신규 사용자계정 생성 시 별지 제 호에 따라 신청서 작성 신원확인\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t등의 절차를 거쳐 발급</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<li>직무변경 퇴직 등 인사이동이 있을 경우 관련 정보시스템 접근권한을 조정</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<li>사용자별 그룹별 접근권한 부여 및 사용자계정 공용 금지</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<li>외부 사용자의 계정부여는 불허하되 부득이한 경우 유효기간을 설정 ,\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t하는 등의 보안조치 후 허용</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<li>비밀번호 등 사용자 식별 인증 수단이 없는 사용자계정 사용 금지</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<li>사용자계정을 주기적 관리자 계정 개월 사용자계정 개월 으로 점검 ( 3 , 6 )\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t하여 접근권한 재검토</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t<li>정보시스템의 계정은 사용목적 및 권한에 따라 관리자계정과 사용자\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t계정으로 구분하여 관리하여야 한다.</li>\r\n");
      out.write("\t \t\t\t\t\t\t\t\t\t<li>관리자계정은 관리자로 지정된 자만이 사용</li>\r\n");
      out.write("\t \t\t\t\t\t\t\t\t\t<li>분임정보보안관리자는 별지 제 호에 따라 소관 정보시스템별 계정발급 6\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t현황을 관리하여야 한다.</li>\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t</ol>\t\r\n");
      out.write("\t\t\t\t\t\t\t    </ol>\r\n");
      out.write("\t\t\t\t\t\t\t    <!-- Trigger the modal with a button -->\r\n");
      out.write("\t\t\t\t\t\t\t\t  <button type=\"button\" class=\"btn btn-warning btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">비밀번호 관리 안내</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t  <!-- Modal -->\r\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t      <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t          <h4 class=\"modal-title\" style=\"font-size:x-large;color:silver;text-align:center;\">비밀번호 관리</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t          <p style=\"font-size:large;color:blue;\">영문자 특수문자 등을 혼합하여 자리 이상으로 정하여야 한다 다만 , 9 . ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t정보시스템에서 기능을 지원하지 않는 경우는 예외로 한다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ol style=\"font-size:medium;color:red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>사용자계정 과 동일하지 않을 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>개인신상 및 부서명칭 등과 관계가 없을 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>일반 사전에 등록된 단어 또는 추측하기 쉬운 단어는 사용을 피할 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>동일단어 또는 숫자를 반복하여 사용하지 말 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>사용된 비밀번호는 재사용하지 말 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>비밀번호를 여러 사람이 공유하여 사용하지 말 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>응용프로그램 등을 이용한 자동 비밀번호 입력기능 사용 금지</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>비밀번호에 유효기간을 선정하여 주기적으로 변경할 것</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li>서버에 등록된 비밀번호는 암호화하여 저장하여야 한다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li>비밀이나 중요자료는 자료별 비밀번호를 부여하여야 한다</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t      \t</div>\r\n");
      out.write("\t\t\t\t\t      <footer class=\"w3-container w3-teal\">\r\n");
      out.write("\t\t\t\t\t        <p style=\"text-align:center;\"><i class=\"fa fa-envira\" style=\"font-size:12px;color:window;\"></i>Modal Message Footer</p>\r\n");
      out.write("\t\t\t\t\t      </footer>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"text-align:center;font-size:small;\">정보보안 기본원칙</h2>\r\n");
      out.write("\t\t\t\t\t<ol style=\"font-size:x-small;\">\r\n");
      out.write("\t\t\t\t\t\t<li>원내 사업 추진 시 발생된 정보자산은 본 기업자체 소유이며 \r\n");
      out.write("\t\t\t\t\t\t\t관리는 각 팀 단위로 한다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>본 기업자체 정보자산은 업무상 필요한 최소한의 접근권한이 부여되어야 한다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>인가된 사용자는 전자정보를 사용함과 동시에 보호할 책임을 가지며,\r\n");
      out.write("\t\t\t\t\t\t\t비인가자는 자신의 업무와 무관한 어떠한 정보자산에도 접근을 시도\r\n");
      out.write("\t\t\t\t\t\t\t해서는 아니 된다.</li>\r\n");
      out.write("\t\t\t\t\t\t<li>본 기업 직원은 정보보안기본지침을 준수 할 의무가 있으며 이를\r\n");
      out.write("\t\t\t\t\t\t\t위반할 시에는 주의 경고 등을 포함한 인사규정에 따라 징계의 사유가 ,\r\n");
      out.write("\t\t\t\t\t\t\t될 수 있다.</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alert alert-info\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align:center;font-size:x-large;color:yellow;\">서버관리구역</h3>\r\n");
      out.write("\t\t\t\t\t<p id=\"redone\">Server Alerts Red For Line is No !!</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"w3-btn w3-red w3-disabled\" >출입제한 Button</a>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<a class=\"w3-button w3-lime\">출입제한 Server 안내</a>\r\n");
      out.write("\t\t\t\t\t<h5 style=\"text-align:center;font-size:large;color:green;\">Server 보안시설</h5>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t<h4  style=\"text-align:center;font-size:x-large;color:fuchsia;\" onclick=\"alertmsg();\">Server Alert</h4>\r\n");
      out.write("\t\t\t\t\t<a class=\"w3-btn w3-lime w3-xlarge\" href=\"/secur/srysite\" onclick=\"sryalert();\">Security Button</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div id=\"myProgress\">\r\n");
      out.write("\t\t\t\t  <div id=\"myBar\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button onclick=\"move()\">Alert Message</button> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h2 style=\"color:red;text-align:center;\">경고 : 본 기업 사이트는 보안사이트로 가입하기전에 꼭 읽어보고 가입하셔야 합니다.</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p style=\"font-size:24px;\"><i class='fas fa-exclamation-triangle' style='font-size:24px;'></i> Maven Company member signup message:</p>\r\n");
      out.write("\t\t\t\t<button class=\"collapsible\" style=\"color:red;font-size:x-large;\">Security Message</button>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t  <p style=\"color:red;text-align:center;\">본 기업사이트는 보안서버로 운영됩니다. 가입시에 절차가 복잡합니다. 본 기업 보안관련내용을 보시고 가입해주시기를\r\n");
      out.write("\t\t\t\t  바랍니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p style=\"font-size:22px;\"><i class='fas fa-exclamation-circle' style='font-size:22px'></i> Message Set:</p>\r\n");
      out.write("\t\t\t\t<button class=\"collapsible\" style=\"color:orange;font-size:large;\">Open Message 1</button>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t  <p style=\"color:navy;\">1. 본 기업에서는 시큐리티 보안자체가 구축되어있습니다. 회원가입이 쉽지않을수 있습니다.\r\n");
      out.write("\t\t\t\t  회원가입시에 중복검사 E-mail 인증절차를 거쳐서 CEO님의 승인결재가 떨어져야 가입이 가능하고\r\n");
      out.write("\t\t\t\t  특히 외부인들에게는 승인절차가 복잡하며 입사자들이 가입할 경우에는 면접때 승인합니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"collapsible\" style=\"color:orange;font-size:large;\">Open Message 2</button>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t  <p style=\"color:green;\">2. 본 기업에서는 친환경을 목적으로 공기청정기를 가동하고 있습니다. 그리고 건강을 목적으로\r\n");
      out.write("\t\t\t\t  담배 흡연하는것을 금지하고 있습니다. 가입하기전에 2번 안내사항을 꼭 읽어보시기를 바랍니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"collapsible\" style=\"color:orange;font-size:large;\">Open Message 3</button>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t  <p style=\"color:fuchsia;\">3. 본 기업에서는 공동체문화를 중심으로 운영하고 있습니다. 웹개발시에\r\n");
      out.write("\t\t\t\t  협업을 위주로 하고 있습니다. 그리고 근무시간으로는 평일에 AM 9:30~PM 6:30으로 근무하고 있고 주4일제로\r\n");
      out.write("\t\t\t\t  운영중입니다. 자세한 것은 메인페이지 etc를 참고해주시기를 바랍니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"danger\">\r\n");
      out.write("\t\t\t\t  <p><strong>경고!</strong> 웹개발시에는 보안프로그램을 사용하고 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"danger\">\r\n");
      out.write("\t\t\t\t  <p><strong>경고!</strong> 사내인트라넷도 운영하는 회사로서 물품반입시에 검색대에서 검사합니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"danger\">\r\n");
      out.write("\t\t\t\t  <p><strong style=\"font-size:x-large;\">경고!</strong> <b style=\"font-size:larger;\">본 기업체는 Maven프로그램과 Spring, SpringBoot 프로그램을 사용하고 git과\r\n");
      out.write("\t\t\t\t  github도 사용중입니다. 그리고 n키퍼 보안프로그램도 동작합니다. 비인가USB 저장매체나 CDP등은 사전에 허가가 있어야\r\n");
      out.write("\t\t\t\t  반입이 가능합니다.</b></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"danger\">\r\n");
      out.write("\t\t\t\t  <p><strong style=\"font-size:xx-large;\">경고!</strong><i class=\"fa fa-cogs\" style=\"font-size:35px;color:red\"></i> <p style=\"font-size:15px;color:teal;\">본 기업사이트\r\n");
      out.write("\t\t\t\t  보안관리는 ADMIN권한으로 관리되고 있습니다. ADMIN권한보유자가 Main Page Menu Admin Page에서 관리자권한으로 보안등급 등을\r\n");
      out.write("\t\t\t\t  조절하고 관리합니다. 그리고 실시간으로 보안점검이 이루어지는 곳으로서 가입하기전에 보안관련내용을 여기에서\r\n");
      out.write("\t\t\t\t  숙지하시고 진행해주시기를 바랍니다.</p></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"danger\">\r\n");
      out.write("\t\t\t\t  <p><strong style=\"font-size:x-large;\">경고!</strong><i class=\"fa fa-expeditedssl\" style=\"font-size:25px;color:maroon;\"></i> <p  style=\"font-size:15px;color:purple;\"> \r\n");
      out.write("\t\t\t\t  본 기업사이트에서 보안SYSTEM Server 관리는 Manager권한 있는 간부급직원들이 관리합니다. \r\n");
      out.write("\t\t\t\t  보안SYSTEM Server는 Tomcat 9.0을 사용하고 데이터베이스를 연계 관리합니다.</p></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<i class='fas fa-exclamation-circle' style='font-size:12px'></i> Red Messages!!\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction move() {\r\n");
      out.write("\t\t\t  alert(\"Red : Maven Company Signup Message Call~!!\")\r\n");
      out.write("\t\t\t  var elem = document.getElementById(\"myBar\");   \r\n");
      out.write("\t\t\t  var width = 1;\r\n");
      out.write("\t\t\t  var id = setInterval(frame, 10);\r\n");
      out.write("\t\t\t  function frame() {\r\n");
      out.write("\t\t\t    if (width >= 100) {\r\n");
      out.write("\t\t\t      clearInterval(id);\r\n");
      out.write("\t\t\t    } else {\r\n");
      out.write("\t\t\t      width++; \r\n");
      out.write("\t\t\t      elem.style.width = width + '%'; \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  }  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar coll = document.getElementsByClassName(\"collapsible\");\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < coll.length; i++) {\r\n");
      out.write("\t\t  coll[i].addEventListener(\"click\", function() {\r\n");
      out.write("\t\t    this.classList.toggle(\"active\");\r\n");
      out.write("\t\t    var content = this.nextElementSibling;\r\n");
      out.write("\t\t    if (content.style.maxHeight){\r\n");
      out.write("\t\t      content.style.maxHeight = null;\r\n");
      out.write("\t\t    } else {\r\n");
      out.write("\t\t      content.style.maxHeight = content.scrollHeight + \"px\";\r\n");
      out.write("\t\t    } \r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction realtimeClock() {\r\n");
      out.write("\t\t\t  document.rtcForm.rtcInput.value = getTimeStamp();\r\n");
      out.write("\t\t\t  setTimeout(\"realtimeClock()\", 1000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction alertmsg(){\r\n");
      out.write("\t\t\talert(\"본 기업 서버관련 내용입니다. 아래 버튼 링크클릭하면 해당 전산서버관리 사이트에 들어가서 보안관련서버 확인 가능합니다.\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction sryalert(){\r\n");
      out.write("\t\t\talert(\"본 기업 전산관리페이지로 연결됩니다.\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
