/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-01-25 08:40:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.secur;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class srysite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/increpas/spring/example/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch19_project_mavenwebsite/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.6.RELEASE.jar", Long.valueOf(1546822982153L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.6.RELEASE.jar", Long.valueOf(1545793331181L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1544682339013L));
    _jspx_dependants.put("jar:file:/C:/increpas/spring/example/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch19_project_mavenwebsite/WEB-INF/lib/spring-webmvc-4.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1462487332000L));
    _jspx_dependants.put("jar:file:/C:/increpas/spring/example/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch19_project_mavenwebsite/WEB-INF/lib/spring-security-taglibs-4.2.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1525766420000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" \r\n");
      out.write(" \t  content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Maven Company Srysite Page</title>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\">\r\n");
      out.write("<link href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.jumbotron{\r\n");
      out.write("\t\tmargin-bottom: 5px;\r\n");
      out.write("\t\tpadding:80px;\r\n");
      out.write("\t\tbackground-color:#90A4AE;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#sec01{\r\n");
      out.write("\t\tcolor:#E0E0E0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#sec01:hover {\r\n");
      out.write("\t\tcolor:blue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.topnav {\r\n");
      out.write("\t  overflow: hidden;\r\n");
      out.write("\t  background-color: #f1f1f1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.topnav a {\r\n");
      out.write("\t  float: left;\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t  text-align: center;\r\n");
      out.write("\t  padding: 14px 16px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t  font-size: 17px;\r\n");
      out.write("\t  border-bottom: 3px solid transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.topnav a:hover {\r\n");
      out.write("\t  border-bottom: 3px solid red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.topnav a.active {\r\n");
      out.write("\t  border-bottom: 3px solid red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.footer{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tline-height: 100px;\r\n");
      out.write("\t\tbackground-color: #444;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top: 200px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t<h1 id=\"sec01\" style=\"font-size:xx-large;\">Maven Security Server Management Site</h1>\r\n");
      out.write("\t\t<h3 style=\"font-size:x-large;\"><i class='fas fa-server' style='font-size:24px'></i> Security Server Management</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t   \t<div class=\"topnav\">\r\n");
      out.write("\t\t  <a class=\"active\" href=\"/secur/srysite\">Home</a>\r\n");
      out.write("\t\t  <a href=\"/main\">Maven Company Main</a>\r\n");
      out.write("\t\t  <a href=\"/user/messages\" title=\"Messages\" onclick=\"messagesone();\">Messages Page</a>\r\n");
      out.write("\t\t  <a href=\"/secur/secboard\">SecBoard</a>\r\n");
      out.write("\t\t  <a href=\"/secur/contact\">Contact</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"padding-left:16px\">\r\n");
      out.write("\t\t  <h2 style=\"text-align:center;font:bold;font-size:xx-large;font-weight:600;\">Maven Security Server Management Site</h2>\r\n");
      out.write("\t\t  <p style=\"text-align:center;\">Maven Security Server 관리 페이지 입니다.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t    <div class=\"col-md-4\">\r\n");
      out.write("\t    \t<button class=\"btn btn-success\" onclick=\"getElementById('demo').innerHTML=Date()\" style='font-size:24px'>Eye Times <i class='fas fa-eye'></i></button>\r\n");
      out.write("\t    \t<a type=\"button\" class=\"btn btn-success\" style='font-size:24px' href=\"\">Server <i class='fas fa-server'></i></a>\r\n");
      out.write("\t    \t<a type=\"button\" class=\"btn btn-success\" style='font-size:24px' href=\"\">Marker-alt <i class='fas fa-map-marker-alt'></i></a>\r\n");
      out.write("\t    \t<a type=\"button\" class=\"btn btn-success\" style='font-size:24px' href=\"\">MemberShip Table <i class='fas fa-table'></i></a>\r\n");
      out.write("\t    \t<p id=\"demo\"></p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-md-4\">\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-md-4\">\r\n");
      out.write("\t    \t<h2>Server 관리자에게 메일 보내기</h2>\r\n");
      out.write("\t\t\t  <form class=\"form-horizontal\" action=\"/action_page.php\">\r\n");
      out.write("\t\t\t  ");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_form_005fform_005f0_reused = false;
      try {
        _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_form_005fform_005f0.setParent(null);
        // /WEB-INF/views/secur/srysite.jsp(100,5) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setAction("/mail/mailSending");
        // /WEB-INF/views/secur/srysite.jsp(100,5) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setMethod("post");
        // /WEB-INF/views/secur/srysite.jsp(100,5) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setModelAttribute("board");
        int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
          if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t    <div class=\"form-group\">\r\n");
              out.write("\t\t\t      <label class=\"control-label col-sm-2\" for=\"email\">Email:</label>\r\n");
              out.write("\t\t\t      <div class=\"col-sm-10\">\r\n");
              out.write("\t\t\t        <p class=\"form-control-static\" id=\"tomail\">as2006a@naver.com</p>\r\n");
              out.write("\t\t\t      </div>\r\n");
              out.write("\t\t\t    </div>\r\n");
              out.write("\t\t\t    <div class=\"form-group\">\r\n");
              out.write("\t\t\t      <label class=\"control-label col-sm-2\" for=\"title\">Email Title:</label>\r\n");
              out.write("\t\t\t      <div class=\"col-sm-10\">          \r\n");
              out.write("\t\t\t        <input class=\"form-control\"\r\n");
              out.write("\t\t\t\t\t\t\t\tpath=\"title\" \r\n");
              out.write("\t\t\t\t\t\t\t\tplaceholder=\"메일 제목을 입력해 주세요\"/>\r\n");
              out.write("\t\t\t\t\t");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_form_005ferrors_005f0_reused = false;
              try {
                _jspx_th_form_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/secur/srysite.jsp(114,5) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setPath("title");
                // /WEB-INF/views/secur/srysite.jsp(114,5) null
                _jspx_th_form_005ferrors_005f0.setDynamicAttribute(null, "class", "error");
                int[] _jspx_push_body_count_form_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f0 = _jspx_th_form_005ferrors_005f0.doStartTag();
                  if (_jspx_th_form_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005ferrors_005f0);
                _jspx_th_form_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_form_005ferrors_005f0_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t      </div>\r\n");
              out.write("\t\t\t    </div>\r\n");
              out.write("\t\t\t    <div class=\"form-group\">\r\n");
              out.write("\t\t\t      <label class=\"control-label col-sm-2\" for=\"email\">Email board</label>\r\n");
              out.write("\t\t\t    </div> \r\n");
              out.write("\t\t\t    <div class=\"form-group\">      \r\n");
              out.write("\t\t\t    \t<textarea class=\"form-control\" id=\"content\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t  path=\"content\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t  placeholder=\"관리자에게 보낼 메일 내용을 입력해 주세요\"></textarea>\r\n");
              out.write("\t\t\t\t\t\t\t");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_form_005ferrors_005f1_reused = false;
              try {
                _jspx_th_form_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/secur/srysite.jsp(124,7) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f1.setPath("content");
                // /WEB-INF/views/secur/srysite.jsp(124,7) null
                _jspx_th_form_005ferrors_005f1.setDynamicAttribute(null, "class", "error");
                int[] _jspx_push_body_count_form_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f1 = _jspx_th_form_005ferrors_005f1.doStartTag();
                  if (_jspx_th_form_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005ferrors_005f1);
                _jspx_th_form_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_form_005ferrors_005f1_reused);
              }
              out.write("\t\r\n");
              out.write("\t\t\t      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
              out.write("\t\t\t        <button type=\"submit\" class=\"btn btn-danger\" >관리자에게 메일 보내기</button>\r\n");
              out.write("\t\t\t      </div>\r\n");
              out.write("\t\t\t    </div>\r\n");
              out.write("\t\t\t    ");
              int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_form_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_form_005fform_005f0);
        _jspx_th_form_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t  </form>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<p>Maven Security Server Site</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js\"></script>\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/lang/summernote-ko-KR.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"#content\").summernote({\r\n");
      out.write("\t\t\theight:400,\r\n");
      out.write("\t\t\t//focus: true,\r\n");
      out.write("\t\t\tdisableResizeEditor:true,\r\n");
      out.write("\t\t\tlang: 'ko-KR',\r\n");
      out.write("\t\t\tcallbacks:{\r\n");
      out.write("\t\t\t\tonImageUpload:sendFile,\r\n");
      out.write("\t\t\t\tonMediaDelete:deleteFile\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction deleteFile(target){\r\n");
      out.write("\t\t\tvar src = target[0].src.substring(21);\r\n");
      out.write("\t\t\tconsole.log(\"src\",src);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/filedelete\",\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tdata:{src:src},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction sendFile(files, editor, welEditable){\r\n");
      out.write("\t\t\t//console.log(files[0]);\r\n");
      out.write("\t\t\tvar data = new FormData();\r\n");
      out.write("\t\t\tdata.append('upload', files[0]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/fileupload\",\r\n");
      out.write("\t\t\t\tcontentType:false,\r\n");
      out.write("\t\t\t\tprocessData:false,\r\n");
      out.write("\t\t\t\tdata:data,\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t//console.log(data);\r\n");
      out.write("\t\t\t\t\t$(\"#content\").summernote(\r\n");
      out.write("\t\t\t\t\t\t\t'editor.insertImage', data.url);\r\n");
      out.write("\t\t\t\t},error:function(error){\r\n");
      out.write("\t\t\t\t\tconsole.error(error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
